Name : Divya Arvind Yadav
Branch : IT 
Task : Numpy opertions

In [2]:
import numpy as np

In [17]:
# array creation using numpy 
a = np.array([1,2,3,4,5])
print(a )

[1 2 3 4 5]


In [13]:
# sort() : This will sort the given array 
a1 = np.array([5,57,13,45,24])
print("Sorted array: ", np.sort(a1))

Sorted array:  [ 5 13 24 45 57]


In [16]:
# unique() = It will find unique values from the array and remove duplicate values 
unique_arr = ([1,2,3,2,3,4])
print(" Unique elemnts : " , np.unique(unique_arr))

 Unique elemnts :  [1 2 3 4]


In [21]:
# concat () : it will concat two arrays 
print("Concated array : " , np.concat(([2,4],[6,8])))

Concated array :  [2 4 6 8]


In [23]:
# in this it will add for each elment in array
a2 = np.array([1,3,5,7,8])
print("Addition of each element by 1 : ", a2+1)

Addition of each element by 1 :  [2 4 6 8 9]


In [24]:
# in this it will multiply each element of array
print("Multiplication of each element by 10: ", a2 * 10)

Multiplication of each element by 10:  [10 30 50 70 80]


In [25]:
# sum()
print("sum of array : ", np.sum(a2))

sum of array :  24


In [26]:
#mean()
print("Mean of array: ", np.mean(a2))

Mean of array:  4.8


In [32]:
#dot(): it performs matrix wise multplication 
arr1 = np.array([[1,2],
                 [3,4],
                 [5,6],
                 [7,8]])

arr2 = np.array([[11,12,13,14],
                 [15,16,17,18]])

dot = np.dot(arr1, arr2)
print(dot)


[[ 41  44  47  50]
 [ 93 100 107 114]
 [145 156 167 178]
 [197 212 227 242]]


In [40]:
# reshape() : it will reshape the array 
arr1.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
# size : it will find the size of an array
print("Size of an array :" , arr1.size)

Size of an array : 8


In [39]:
# shape(): it will print shape of an arrray means rows & columns 
print(arr1.shape)

(4, 2)


In [42]:
#ndim() : no. of dimensions 
print(arr1.ndim)

2
